// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// SVG paths live in /public/brand-icons.svg (referenced with <use>).
export type BrandIcon = { title: string; hex: string };

export const brandIcons = {
  "github": {
    "title": "GitHub",
    "hex": "#181717"
  },
  "python": {
    "title": "Python",
    "hex": "#3776AB"
  },
  "numpy": {
    "title": "NumPy",
    "hex": "#013243"
  },
  "postgresql": {
    "title": "PostgreSQL",
    "hex": "#4169E1"
  },
  "docker": {
    "title": "Docker",
    "hex": "#2496ED"
  },
  "flask": {
    "title": "Flask",
    "hex": "#3BABC3"
  },
  "flutter": {
    "title": "Flutter",
    "hex": "#02569B"
  },
  "dart": {
    "title": "Dart",
    "hex": "#0175C2"
  },
  "angular": {
    "title": "Angular",
    "hex": "#0F0F11"
  },
  "springboot": {
    "title": "Spring Boot",
    "hex": "#6DB33F"
  },
  "typescript": {
    "title": "TypeScript",
    "hex": "#3178C6"
  },
  "javascript": {
    "title": "JavaScript",
    "hex": "#F7DF1E"
  },
  "html5": {
    "title": "HTML5",
    "hex": "#E34F26"
  },
  "css": {
    "title": "CSS",
    "hex": "#663399"
  },
  "nextdotjs": {
    "title": "Next.js",
    "hex": "#000000"
  },
  "vercel": {
    "title": "Vercel",
    "hex": "#000000"
  },
  "cisco": {
    "title": "Cisco",
    "hex": "#1BA0D7"
  },
  "huawei": {
    "title": "Huawei",
    "hex": "#FF0000"
  },
  "arduino": {
    "title": "Arduino",
    "hex": "#00878F"
  },
  "linux": {
    "title": "Linux",
    "hex": "#FCC624"
  },
  "sonarqubecloud": {
    "title": "SonarQube Cloud",
    "hex": "#126ED3"
  },
  "openjdk": {
    "title": "OpenJDK",
    "hex": "#000000"
  },
  "c": {
    "title": "C",
    "hex": "#A8B9CC"
  },
  "whatsapp": {
    "title": "WhatsApp",
    "hex": "#25D366"
  },
  "nxp": {
    "title": "NXP",
    "hex": "#000000"
  },
  "git": {
    "title": "Git",
    "hex": "#F03C2E"
  },
  "ubuntu": {
    "title": "Ubuntu",
    "hex": "#E95420"
  },
  "mysql": {
    "title": "MySQL",
    "hex": "#4479A1"
  },
  "h2database": {
    "title": "H2 Database",
    "hex": "#09476B"
  },
  "bootstrap": {
    "title": "Bootstrap",
    "hex": "#7952B3"
  },
  "thymeleaf": {
    "title": "Thymeleaf",
    "hex": "#005F0F"
  },
  "renault": {
    "title": "Renault",
    "hex": "#FFCC33"
  },
  "scikitlearn": {
    "title": "scikit-learn",
    "hex": "#F7931E"
  },
  "jupyter": {
    "title": "Jupyter",
    "hex": "#F37626"
  },
  "uml": {
    "title": "UML",
    "hex": "#FABD14"
  },
  "linkedin": {
    "title": "LinkedIn",
    "hex": "#0A66C2"
  }
} as const satisfies Record<string, BrandIcon>;

export type BrandIconKey = keyof typeof brandIcons;

/** Versioned by content hash, so browsers refetch the sprite only when it changes. */
export const BRAND_SPRITE = "/brand-icons.svg?v=ce7d33a2";
