// Extracts only the brand icons used by the site from `simple-icons`
// into a small typed module, so no client bundle ships the full icon set.
// Usage: node scripts/generate-icons.mjs
import * as icons from "simple-icons";
import { writeFileSync } from "node:fs";

const wanted = {
  github: "siGithub",
  python: "siPython",
  numpy: "siNumpy",
  postgresql: "siPostgresql",
  docker: "siDocker",
  flask: "siFlask",
  flutter: "siFlutter",
  dart: "siDart",
  angular: "siAngular",
  springboot: "siSpringboot",
  typescript: "siTypescript",
  javascript: "siJavascript",
  html5: "siHtml5",
  css: "siCss",
  nextdotjs: "siNextdotjs",
  vercel: "siVercel",
  cisco: "siCisco",
  huawei: "siHuawei",
  arduino: "siArduino",
  linux: "siLinux",
  sonarqubecloud: "siSonarqubecloud",
  openjdk: "siOpenjdk",
  c: "siC",
  whatsapp: "siWhatsapp",
  nxp: "siNxp",
  git: "siGit",
  ubuntu: "siUbuntu",
  mysql: "siMysql",
  h2database: "siH2database",
  bootstrap: "siBootstrap",
  thymeleaf: "siThymeleaf",
  renault: "siRenault",
  scikitlearn: "siScikitlearn",
  jupyter: "siJupyter",
  uml: "siUml",
};

const out = {};
for (const [key, name] of Object.entries(wanted)) {
  const icon = icons[name];
  if (!icon) {
    console.warn(`missing icon: ${name}`);
    continue;
  }
  out[key] = { title: icon.title, hex: `#${icon.hex}`, path: icon.path };
}

// Brand marks absent from simple-icons (removed at the brands' request).
out.linkedin = {
  title: "LinkedIn",
  hex: "#0A66C2",
  path: "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z",
};

const body = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
export type BrandIcon = { title: string; hex: string; path: string };

export const brandIcons = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, BrandIcon>;

export type BrandIconKey = keyof typeof brandIcons;
`;
writeFileSync(new URL("../src/lib/brand-icons.ts", import.meta.url), body);
console.log(`wrote ${Object.keys(out).length} icons`);
